# Generated by Django 4.1 on 2023-07-16 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_id", models.CharField(max_length=120)),
                ("problem_title", models.CharField(max_length=200)),
                ("problem_statement", models.TextField(max_length=10000)),
                ("difficulty", models.CharField(max_length=100)),
                ("count_solved", models.IntegerField(default=0)),
                ("count_attempted", models.IntegerField(default=0)),
                (
                    "user_uploaded",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
