# Generated by Django 4.1 on 2023-07-16 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("code_execution", "0002_alter_problems_difficulty"),
    ]

    operations = [
        migrations.RenameModel(old_name="Problems", new_name="Problem",),
    ]
